name = "bigurl-workers"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[[d1_databases]]
binding = "DB"
database_name = "bigurl_db"
database_id = "__REPLACE_WITH_D1_ID__"

[[kv_namespaces]]
binding = "KV"
id = "__REPLACE_WITH_KV_ID__"

[[analytics_engine_datasets]]
binding = "ANALYTICS"








